language: node_js
node_js:
  - 4.2.3
# whitelist
branches:
  only:
    - master
    - develop
    - test
  except:
    - /^feature.*$/
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm cache clean
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
after_script:
  - grunt test:coverage:unit || true
  - grunt coveralls
services: mongodb
